
GET  http://localhost:3002/api/getsubscribeduser


###
POST http://localhost:3002/api/adduser
Content-Type: application/json

{
    "name": "max",
    "email": "max.doe@example.com",
    "password": "secretpassword",
    "is_subscribed":true,
    "subscription_type": "premium"
}